Tests(not complete) Added OPEN AI integration

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -11,15 +11,15 @@ services:
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
       - POSTGRES_DB=${POSTGRES_DB}
 
-  app:
-    container_name: app
+  backend:
+    container_name: backend
     env_file:
       - ./.env
     build:
       context: ./server
     command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
     volumes:
-      - ./server:/app
+      - ./server:/workdir_docker
     ports:
       - 8000:8000
     restart: always
@@ -37,12 +37,12 @@ services:
       dockerfile: Dockerfile
     command: celery -A app.celery_worker.celery worker --loglevel=info
     volumes:
-      - ./server:/app
+      - ./server:/workdir_docker
     environment:
       - CELERY_BROKER_URL=${CELERY_BROKER_URL}
       - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
     depends_on:
-      - app
+      - backend
       - redis
 
   pgadmin:
@@ -69,6 +69,41 @@ services:
       - CELERY_BROKER_URL=${CELERY_BROKER_URL}
       - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
     depends_on:
-      - app
+      - backend
       - redis
       - celery_worker
+
+  test_db:
+    container_name: test_postgres_cargenius
+    image: postgres
+    restart: always
+    env_file:
+      - ./.env
+    environment:
+      - POSTGRES_USER=${TEST_POSTGRES_USER}
+      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
+      - POSTGRES_DB=${TEST_POSTGRES_DB}
+
+  test:
+    container_name: test_cargenius
+    build:
+      context: ./server
+      dockerfile: Dockerfile
+    env_file:
+      - ./.env
+    environment:
+      - PYTHONPATH=/workdir_docker
+      - USE_TEST_DB=1
+    command: >
+      bash -c "
+        echo 'Running Alembic migration...' &&
+        alembic -c alembic_test.ini upgrade head || (echo 'Alembic failed!' && exit 1) &&
+        echo 'Waiting for DB...' &&
+        sleep 5 &&
+        echo 'Running tests...' &&
+        pytest --maxfail=1 --tb=short -q"
+
+    volumes:
+      - ./server:/workdir_docker
+    depends_on:
+      - test_db
